# Minimum iOS version
platform :ios, '12.0'

# Using swift, so Dynamic Frameworks required!
use_frameworks!

def bvsdk_pod
  pod 'BVSDK', :path => "../../"
  pod 'BVSDK/BVCurations', :path => "../../"
  pod 'BVSDK/BVCurationsUI', :path => "../../"
  pod 'BVSDK/BVRecommendations', :path => "../../"
  pod 'BVSDK/BVNotifications', :path => "../../"
end

def common_pods
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
  pod 'SwiftyJSON'
  bvsdk_pod
end

target 'BVSDKDemo' do
  common_pods
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage', '~> 4.4.3'
  pod 'Google-Mobile-Ads-SDK'
  pod 'HCSStarRatingView'
  pod 'NVActivityIndicatorView', '~> 4.4.1'
  pod 'FontAwesomeKit/FontAwesome'
  pod 'XLActionController', '~> 3.0'
  pod 'youtube-ios-player-helper'
  pod 'SDForms', :git => 'https://github.com/austimkelly/SDForms.git', :branch => 'master'
  pod 'FBSDKCoreKit', '~> 4.44.0'
  pod 'FBSDKLoginKit', '~> 4.44.0'
  pod 'FBSDKShareKit', '~> 4.44.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
