# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

def common_pods
	
	pod 'OHHTTPStubs', '5.1.0'
	pod 'SwiftyJSON'

end

target 'BVSDKDemo' do

	common_pods

	pod 'Fabric'
	pod 'Crashlytics'
	pod 'SDWebImage'
	pod 'Google-Mobile-Ads-SDK'
	pod 'HCSStarRatingView'
	pod 'NVActivityIndicatorView'
	pod 'FontAwesomeKit/FontAwesome'
    pod 'XLActionController', '~> 3.0'
    pod "youtube-ios-player-helper", "~> 0.1.6"
    pod 'SDForms', :git => 'https://github.com/austimkelly/SDForms.git', :branch => 'master'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'

end

target 'Curations Custom Post Extension' do

	common_pods
	pod 'BVSDK/BVCurations', :path => "../../"

end


post_install do |installer|
    installer.pods_project.targets.each do |target|

        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end


