use_frameworks!

target 'BVSDK-Tests' do
    pod "BVSDK", :path => "../"
    pod "BVSDK/BVConversations", :path => "../"
    pod "BVSDK/BVAdvertising", :path => "../"
    pod "BVSDK/BVRecommendations", :path => "../"
    pod "BVSDK/BVCurations", :path => "../"
    pod "BVSDK/BVLocation", :path => "../"
    pod 'OHHTTPStubs', '~> 5.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
        
    end
end
