use_frameworks!

target 'BVSDK-Tests' do
    pod "BVSDK", :path => "../"
    pod "BVSDK/BVConversations", :path => "../"
    pod "BVSDK/BVAdvertising", :path => "../"
    pod "BVSDK/BVRecommendations", :path => "../"
    pod "BVSDK/BVCurations", :path => "../"
    pod 'OHHTTPStubs'
end

