platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

use_frameworks!

target 'RecommendationsExample' do
	pod "BVSDK/BVRecommendations", :path => "../../../"
	pod 'SDWebImage'
	pod 'HCSStarRatingView'
end