# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Curations' do
	pod "BVSDK/BVCurations", :path => "../../"
	pod 'SDWebImage'
	pod 'NVActivityIndicatorView'
    pod 'OHHTTPStubs'
    pod 'HCSStarRatingView'
    pod "youtube-ios-player-helper", "~> 0.1.4"
end

target 'CurationsTests' do
	pod "BVSDK/BVCurations", :path => "../../"
	pod 'SDWebImage'
	pod 'NVActivityIndicatorView'
	pod 'OHHTTPStubs'
    pod 'HCSStarRatingView'
    pod "youtube-ios-player-helper", "~> 0.1.4"
end

