# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'CurationsExample' do
	pod 'BVSDK/BVCurations', :path => "../../../"
	pod 'BVSDK/BVCurationsUI', :path => "../../../"
    pod 'SDWebImage'
end

