source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TargetedAdsDemo' do

	pod "BVSDK/BVAdvertising", :path => "../../../"
	pod 'Google-Mobile-Ads-SDK'	
	pod 'MBProgressHUD', '~> 0.9.1'
	pod 'FontAwesomeKit/FontAwesome'
end
