source 'https://github.com/CocoaPods/Specs.git'

target 'TargetedAdsDemo' do

	pod "BVSDK/BVAdvertising", :path => "../../"
# NOTE: When using CocooaPods with "use_frameworks!" and a Swift app you cannot have a dependency # on a library that is not dynamic. You must install the SDK manually if using BVAdvertising.
	pod 'Google-Mobile-Ads-SDK', '~> 7.6'	
	pod 'MBProgressHUD', '~> 0.9.1'
	pod 'FontAwesomeKit/FontAwesome'

end
