//
//  BVPersonalizationEvent.h
//  BVSDK
//
//  Copyright © 2017 Bazaarvoice. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "BVAnalyticEvent.h"

#define PERSONALIZATION_SCHEMA   @{@"cl": @"Personalization",@"type": @"ProfileMobile",@"bvProduct": @"ShopperMarketing"}

/**
 Set user information. Associates a user profile with device for taylored advertising and recommendations.
 Use of this method requires that a valid key has been set for apiKeyShopperMarketing.
*/
@interface BVPersonalizationEvent : NSObject <BVAnalyticEvent>

- (id _Nonnull)initWithUserAuthenticationString:(NSString * _Nonnull)uas;

- (nonnull instancetype) __unavailable init;

/// Generated user authentication string endoded with shared secret. Generated by your server-side implementation.
@property (nonatomic, strong, readonly) NSString* _Nonnull uas;

@end
