name: BVSDK Sonarqube Scan CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
  SONAR_URL: ${{ secrets.SONAR_URL }}

jobs:
  build:
    
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: Homebrew/actions/setup-homebrew@master

    - name: Select Xcode
      run: sudo Xcode-select -switch /Applications/Xcode_13.1.app

    - name: GenerateBuildConfigCoverage
      run: sh '././ci_scripts/generateBuildConfigCoverage.sh'

    - uses: actions/upload-artifact@v2
      with:
        name: BuildConfigAndCoverage
        path: |
          ${{ github.workspace }}/build
          ${{ github.workspace }}/build_wrapper_output_directory
          ${{ github.workspace }}/sonarqube-generic-coverage.xml
        retention-days: 1

  scan:
    needs: build

    runs-on: [self-hosted,qa]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v2
      with:
        name: BuildConfigAndCoverage
        path: ${{ github.workspace }}
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'


    - name: Sonarqube Scan
      run: sh '././ci_scripts/sonarscan.sh'
