platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'BVProductRecsExample' do
	pod "BVSDK/BVRecommendations", :path => "../../"
	pod 'SDWebImage'
	pod 'NVActivityIndicatorView'
	pod 'HCSStarRatingView'
end

target 'BVProductRecsExampleTests' do
	pod "BVSDK/BVRecommendations", :path => "../../"
end	