platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

link_with 'BVProductRecsExample', 'BVProductRecsExampleTests', 'BVProductRecsExampleUITests'

target 'BVProductRecsExample' do
	pod "BVSDK/BVRecommendationsUI", :path => "../../"
	pod 'SDWebImage'
end

target 'BVProductRecsExampleTests' do
	pod "BVSDK/BVRecommendationsUI", :path => "../../"
	pod 'SDWebImage'
	pod 'FBSnapshotTestCase/Core'
end	

target 'BVProductRecsExampleUITests' do
	pod "BVSDK/BVRecommendationsUI", :path => "../../"
	pod 'SDWebImage'
end